# Generated by Django 3.2.5 on 2021-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('createdOn', models.DateTimeField()),
                ('employeeId', models.CharField(max_length=30)),
            ],
        ),
    ]
